//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ACC_OFF {
            get {
                object obj = ResourceManager.GetObject("ACC_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ACC_ON {
            get {
                object obj = ResourceManager.GetObject("ACC_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert2 {
            get {
                object obj = ResourceManager.GetObject("alert2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bad {
            get {
                object obj = ResourceManager.GetObject("bad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckedSymbol {
            get {
                object obj = ResourceManager.GetObject("CheckedSymbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMP_OFF {
            get {
                object obj = ResourceManager.GetObject("COMP_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMP_ON {
            get {
                object obj = ResourceManager.GetObject("COMP_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;/Document&gt;
        ///&lt;/kml&gt;.
        /// </summary>
        internal static string Final_Bot {
            get {
                return ResourceManager.GetString("Final_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;kml xmlns=&quot;http://www.opengis.net/kml/2.2&quot; xmlns:gx=&quot;http://www.google.com/kml/ext/2.2&quot; xmlns:kml=&quot;http://www.opengis.net/kml/2.2&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///
        ///	&lt;Document&gt;
        ///		&lt;name&gt;.
        /// </summary>
        internal static string Final_Top_1 {
            get {
                return ResourceManager.GetString("Final_Top_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/name&gt;
        ///		&lt;open&gt;1&lt;/open&gt;
        ///
        ///		&lt;Style id=&quot;style_line&quot;&gt;
        ///			&lt;LineStyle&gt;
        ///				&lt;color&gt;730000FF&lt;/color&gt;
        ///				&lt;width&gt;2&lt;/width&gt;
        ///			&lt;/LineStyle&gt;
        ///		&lt;/Style&gt;
        ///		
        ///		&lt;Style id=&quot;START&quot;&gt;
        ///			&lt;IconStyle&gt;
        ///				&lt;Icon&gt;
        ///					&lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/arrow-reverse.png&lt;/href&gt;
        ///				&lt;/Icon&gt;
        ///			&lt;/IconStyle&gt;
        ///			&lt;LabelStyle&gt;
        ///				&lt;color&gt;FFFFFFFF&lt;/color&gt;
        ///				&lt;scale&gt;1&lt;/scale&gt;
        ///			&lt;/LabelStyle&gt;
        ///		&lt;/Style&gt;
        ///		
        ///		&lt;Style id=&quot;STOP&quot;&gt;
        ///			&lt;IconStyle&gt;
        ///				&lt;Icon&gt;
        ///					&lt;href&gt;http://maps.google.com/mapfiles/km [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Final_Top_2 {
            get {
                return ResourceManager.GetString("Final_Top_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;/Folder&gt;
        ///.
        /// </summary>
        internal static string Folder_Bot {
            get {
                return ResourceManager.GetString("Folder_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;Folder&gt;
        ///			&lt;name&gt;Placemarks&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Generics_Top {
            get {
                return ResourceManager.GetString("Folder_Generics_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;Folder&gt;
        ///			&lt;name&gt;Path&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Path_Top {
            get {
                return ResourceManager.GetString("Folder_Path_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;Folder&gt;
        ///			&lt;name&gt;Waypoints&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Waypoints_Top {
            get {
                return ResourceManager.GetString("Folder_Waypoints_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYRO_OFF {
            get {
                object obj = ResourceManager.GetObject("GYRO_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYRO_ON {
            get {
                object obj = ResourceManager.GetObject("GYRO_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;LookAt&gt;
        ///			&lt;longitude&gt;.
        /// </summary>
        internal static string lookat1 {
            get {
                return ResourceManager.GetString("lookat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/longitude&gt;
        ///			&lt;latitude&gt;.
        /// </summary>
        internal static string lookat2 {
            get {
                return ResourceManager.GetString("lookat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/latitude&gt;
        ///			&lt;altitude&gt;.
        /// </summary>
        internal static string lookat3 {
            get {
                return ResourceManager.GetString("lookat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/altitude&gt;
        ///			&lt;heading&gt;0&lt;/heading&gt;
        ///			&lt;range&gt;1000&lt;/range&gt;
        ///			&lt;altitudeMode&gt;relativeToGround&lt;/altitudeMode&gt;
        ///			&lt;gx:altitudeMode&gt;relativeToSeaFloor&lt;/gx:altitudeMode&gt;
        ///		&lt;/LookAt&gt;
        ///.
        /// </summary>
        internal static string lookat4 {
            get {
                return ResourceManager.GetString("lookat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagID	timestamp	location-lat	location-long	height-above-msl	ground-speed	satellite-count	hdop	maximum-signal-strengt
        ///.
        /// </summary>
        internal static string Movebank_Top {
            get {
                return ResourceManager.GetString("Movebank_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 					&lt;/coordinates&gt;
        ///				&lt;/LineString&gt;
        ///			&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Path_Bot {
            get {
                return ResourceManager.GetString("Path_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;Placemark&gt;
        ///				&lt;name&gt;Path&lt;/name&gt;
        ///				&lt;styleUrl&gt;#style_line&lt;/styleUrl&gt;
        ///				&lt;LineString&gt;
        ///					&lt;tessellate&gt;1&lt;/tessellate&gt;
        ///					&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;
        ///					&lt;coordinates&gt;
        ///.
        /// </summary>
        internal static string Path_Top {
            get {
                return ResourceManager.GetString("Path_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 				&lt;/Point&gt;
        ///			&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Generic_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;Placemark&gt;
        ///				&lt;name&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_1 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/name&gt;
        ///				&lt;styleUrl&gt;#classe.
        /// </summary>
        internal static string Placemarks_Generic_Top_2 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/styleUrl&gt;
        ///				&lt;ExtendedData&gt;
        ///					&lt;Data name=&quot;Altitude&quot;&gt;
        ///						&lt;value&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_3 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/value&gt;
        ///					&lt;/Data&gt;
        ///					&lt;Data name=&quot;Speed&quot;&gt;
        ///						&lt;value&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_4 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/value&gt;
        ///					&lt;/Data&gt;
        ///				&lt;/ExtendedData&gt;
        ///				&lt;Point&gt;
        ///					&lt;altitudeMode&gt;absolute&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_5 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_6 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;/Point&gt;
        ///		&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Start_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Start_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;Placemark&gt;
        ///			&lt;name&gt;START&lt;/name&gt;
        ///			&lt;styleUrl&gt;#START&lt;/styleUrl&gt;
        ///			&lt;Point&gt;
        ///				&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Start_Top {
            get {
                return ResourceManager.GetString("Placemarks_Start_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;/Point&gt;
        ///		&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Stop_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Stop_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;Placemark&gt;
        ///			&lt;name&gt;STOP&lt;/name&gt;
        ///			&lt;styleUrl&gt;#STOP&lt;/styleUrl&gt;
        ///			&lt;Point&gt;
        ///				&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Stop_Top {
            get {
                return ResourceManager.GetString("Placemarks_Stop_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLAY_BUTTON {
            get {
                object obj = ResourceManager.GetObject("PLAY_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STOP_BUTTON {
            get {
                object obj = ResourceManager.GetObject("STOP_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technosmartLogo {
            get {
                object obj = ResourceManager.GetObject("technosmartLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technosmartLogoBlurred {
            get {
                object obj = ResourceManager.GetObject("technosmartLogoBlurred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Xceed_Wpf_Toolkit {
            get {
                object obj = ResourceManager.GetObject("Xceed_Wpf_Toolkit", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
