//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ACC_OFF {
            get {
                object obj = ResourceManager.GetObject("ACC_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ACC_ON {
            get {
                object obj = ResourceManager.GetObject("ACC_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert2 {
            get {
                object obj = ResourceManager.GetObject("alert2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bad {
            get {
                object obj = ResourceManager.GetObject("bad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckedSymbol {
            get {
                object obj = ResourceManager.GetObject("CheckedSymbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMP_OFF {
            get {
                object obj = ResourceManager.GetObject("COMP_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMP_ON {
            get {
                object obj = ResourceManager.GetObject("COMP_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a -h: 
        ///this help
        ///
        ///-c: &lt;file name&gt;
        ///The raw file to be converted.
        ///
        ///-txt:
        ///	true
        ///	false
        ///Add a txt file with fixes and events
        ///
        ///-kml
        ///	true
        ///	false
        ///Add a kml files with GPS fixes and path.
        ///
        ///-pressUnit:
        ///	bar
        ///	meter
        ///Pressure is converted in height if \&quot;meters\&quot; is selected.
        ///
        ///-pressOffset:
        ///	integral number
        ///If pressure to height conversion in required, this value represents the air pressure value at 0m.
        ///
        ///-dateFormat:
        ///	dd/MM/yyyy
        ///	MM/dd/yyyy
        ///	yyyy/MM/dd
        ///	yyyy/dd/MM
        ///How the date has to be disp [stringa troncata]&quot;;.
        /// </summary>
        internal static string console_help {
            get {
                return ResourceManager.GetString("console_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	&lt;/Document&gt;
        ///&lt;/kml&gt;.
        /// </summary>
        internal static string Final_Bot {
            get {
                return ResourceManager.GetString("Final_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;kml xmlns=&quot;http://www.opengis.net/kml/2.2&quot; xmlns:gx=&quot;http://www.google.com/kml/ext/2.2&quot; xmlns:kml=&quot;http://www.opengis.net/kml/2.2&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///
        ///	&lt;Document&gt;
        ///		&lt;name&gt;.
        /// </summary>
        internal static string Final_Top_1 {
            get {
                return ResourceManager.GetString("Final_Top_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/name&gt;
        ///		&lt;open&gt;1&lt;/open&gt;
        ///
        ///		&lt;Style id=&quot;style_line&quot;&gt;
        ///			&lt;LineStyle&gt;
        ///				&lt;color&gt;730000FF&lt;/color&gt;
        ///				&lt;width&gt;2&lt;/width&gt;
        ///			&lt;/LineStyle&gt;
        ///		&lt;/Style&gt;
        ///		
        ///		&lt;Style id=&quot;START&quot;&gt;
        ///			&lt;IconStyle&gt;
        ///				&lt;Icon&gt;
        ///					&lt;href&gt;http://maps.google.com/mapfiles/kml/shapes/arrow-reverse.png&lt;/href&gt;
        ///				&lt;/Icon&gt;
        ///			&lt;/IconStyle&gt;
        ///			&lt;LabelStyle&gt;
        ///				&lt;color&gt;FFFFFFFF&lt;/color&gt;
        ///				&lt;scale&gt;1&lt;/scale&gt;
        ///			&lt;/LabelStyle&gt;
        ///		&lt;/Style&gt;
        ///		
        ///		&lt;Style id=&quot;STOP&quot;&gt;
        ///			&lt;IconStyle&gt;
        ///				&lt;Icon&gt;
        ///					&lt;href&gt;http://maps.google.com/mapfiles/km [stringa troncata]&quot;;.
        /// </summary>
        internal static string Final_Top_2 {
            get {
                return ResourceManager.GetString("Final_Top_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;/Folder&gt;
        ///.
        /// </summary>
        internal static string Folder_Bot {
            get {
                return ResourceManager.GetString("Folder_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;Folder&gt;
        ///			&lt;name&gt;Placemarks&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Generics_Top {
            get {
                return ResourceManager.GetString("Folder_Generics_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;Folder&gt;
        ///			&lt;name&gt;Path&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Path_Top {
            get {
                return ResourceManager.GetString("Folder_Path_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;Folder&gt;
        ///			&lt;name&gt;Waypoints&lt;/name&gt;
        ///.
        /// </summary>
        internal static string Folder_Waypoints_Top {
            get {
                return ResourceManager.GetString("Folder_Waypoints_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYRO_OFF {
            get {
                object obj = ResourceManager.GetObject("GYRO_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GYRO_ON {
            get {
                object obj = ResourceManager.GetObject("GYRO_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;LookAt&gt;
        ///			&lt;longitude&gt;.
        /// </summary>
        internal static string lookat1 {
            get {
                return ResourceManager.GetString("lookat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/longitude&gt;
        ///			&lt;latitude&gt;.
        /// </summary>
        internal static string lookat2 {
            get {
                return ResourceManager.GetString("lookat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/latitude&gt;
        ///			&lt;altitude&gt;.
        /// </summary>
        internal static string lookat3 {
            get {
                return ResourceManager.GetString("lookat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/altitude&gt;
        ///			&lt;heading&gt;0&lt;/heading&gt;
        ///			&lt;range&gt;1000&lt;/range&gt;
        ///			&lt;altitudeMode&gt;relativeToGround&lt;/altitudeMode&gt;
        ///			&lt;gx:altitudeMode&gt;relativeToSeaFloor&lt;/gx:altitudeMode&gt;
        ///		&lt;/LookAt&gt;
        ///.
        /// </summary>
        internal static string lookat4 {
            get {
                return ResourceManager.GetString("lookat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;style&gt;
        ///      .map {
        ///        height: 400px;
        ///        width: 100%;
        ///      }
        ///    &lt;/style&gt;
        ///    &lt;script src=&quot;https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js&quot;&gt;&lt;/script&gt;
        ///    &lt;title&gt;OpenLayers example&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h2&gt;My Map&lt;/h2&gt;
        ///    &lt;div id=&quot;map&quot; class=&quot;map&quot;&gt;&lt;/ [stringa troncata]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TagID	timestamp	location-lat	location-long	height-above-msl	ground-speed	satellite-count	hdop	maximum-signal-strengt
        ///.
        /// </summary>
        internal static string Movebank_Top {
            get {
                return ResourceManager.GetString("Movebank_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 					&lt;/coordinates&gt;
        ///				&lt;/LineString&gt;
        ///			&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Path_Bot {
            get {
                return ResourceManager.GetString("Path_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 			&lt;Placemark&gt;
        ///				&lt;name&gt;Path&lt;/name&gt;
        ///				&lt;styleUrl&gt;#style_line&lt;/styleUrl&gt;
        ///				&lt;LineString&gt;
        ///					&lt;tessellate&gt;1&lt;/tessellate&gt;
        ///					&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;
        ///					&lt;coordinates&gt;
        ///.
        /// </summary>
        internal static string Path_Top {
            get {
                return ResourceManager.GetString("Path_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 				&lt;/Point&gt;
        ///			&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Generic_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 			&lt;Placemark&gt;
        ///				&lt;name&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_1 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/name&gt;
        ///				&lt;styleUrl&gt;#classe.
        /// </summary>
        internal static string Placemarks_Generic_Top_2 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/styleUrl&gt;
        ///				&lt;ExtendedData&gt;
        ///					&lt;Data name=&quot;Altitude&quot;&gt;
        ///						&lt;value&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_3 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/value&gt;
        ///					&lt;/Data&gt;
        ///					&lt;Data name=&quot;Speed&quot;&gt;
        ///						&lt;value&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_4 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/value&gt;
        ///					&lt;/Data&gt;
        ///				&lt;/ExtendedData&gt;
        ///				&lt;Point&gt;
        ///					&lt;altitudeMode&gt;absolute&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_5 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Generic_Top_6 {
            get {
                return ResourceManager.GetString("Placemarks_Generic_Top_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 			&lt;/Point&gt;
        ///		&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Start_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Start_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;Placemark&gt;
        ///			&lt;name&gt;START&lt;/name&gt;
        ///			&lt;styleUrl&gt;#START&lt;/styleUrl&gt;
        ///			&lt;Point&gt;
        ///				&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Start_Top {
            get {
                return ResourceManager.GetString("Placemarks_Start_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 			&lt;/Point&gt;
        ///		&lt;/Placemark&gt;
        ///.
        /// </summary>
        internal static string Placemarks_Stop_Bot {
            get {
                return ResourceManager.GetString("Placemarks_Stop_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 		&lt;Placemark&gt;
        ///			&lt;name&gt;STOP&lt;/name&gt;
        ///			&lt;styleUrl&gt;#STOP&lt;/styleUrl&gt;
        ///			&lt;Point&gt;
        ///				&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;.
        /// </summary>
        internal static string Placemarks_Stop_Top {
            get {
                return ResourceManager.GetString("Placemarks_Stop_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLAY_BUTTON {
            get {
                object obj = ResourceManager.GetObject("PLAY_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STOP_BUTTON {
            get {
                object obj = ResourceManager.GetObject("STOP_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technosmartLogo {
            get {
                object obj = ResourceManager.GetObject("technosmartLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technosmartLogoBlurred {
            get {
                object obj = ResourceManager.GetObject("technosmartLogoBlurred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_background_loading {
            get {
                object obj = ResourceManager.GetObject("tile_background_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile_background_offline {
            get {
                object obj = ResourceManager.GetObject("tile_background_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
