//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("millibars")]
        public string CONV_PRESSURE_UNIT {
            get {
                return ((string)(this["CONV_PRESSURE_UNIT"]));
            }
            set {
                this["CONV_PRESSURE_UNIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1016")]
        public double CONV_PRESSURE_OFFSET {
            get {
                return ((double)(this["CONV_PRESSURE_OFFSET"]));
            }
            set {
                this["CONV_PRESSURE_OFFSET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte CONV_DATE_FORMAT {
            get {
                return ((byte)(this["CONV_DATE_FORMAT"]));
            }
            set {
                this["CONV_DATE_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte CONV_TIME_FORMAT {
            get {
                return ((byte)(this["CONV_TIME_FORMAT"]));
            }
            set {
                this["CONV_TIME_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONV_FILL_EMPTY {
            get {
                return ((bool)(this["CONV_FILL_EMPTY"]));
            }
            set {
                this["CONV_FILL_EMPTY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONV_SAME_COLUMN {
            get {
                return ((bool)(this["CONV_SAME_COLUMN"]));
            }
            set {
                this["CONV_SAME_COLUMN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONV_TIME_OVERRIDE {
            get {
                return ((bool)(this["CONV_TIME_OVERRIDE"]));
            }
            set {
                this["CONV_TIME_OVERRIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime CONV_TIME {
            get {
                return ((global::System.DateTime)(this["CONV_TIME"]));
            }
            set {
                this["CONV_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONV_METADATA {
            get {
                return ((bool)(this["CONV_METADATA"]));
            }
            set {
                this["CONV_METADATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CONV_LEAP_SECONDS {
            get {
                return ((int)(this["CONV_LEAP_SECONDS"]));
            }
            set {
                this["CONV_LEAP_SECONDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONV_NON_GPS {
            get {
                return ((bool)(this["CONV_NON_GPS"]));
            }
            set {
                this["CONV_NON_GPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CONV_PROXIMITY {
            get {
                return ((bool)(this["CONV_PROXIMITY"]));
            }
            set {
                this["CONV_PROXIMITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_BACKGROUND_IMAGE {
            get {
                return ((string)(this["PATH_BACKGROUND_IMAGE"]));
            }
            set {
                this["PATH_BACKGROUND_IMAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_SCHEDULE {
            get {
                return ((string)(this["PATH_SCHEDULE"]));
            }
            set {
                this["PATH_SCHEDULE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_DATA_SAVE {
            get {
                return ((string)(this["PATH_DATA_SAVE"]));
            }
            set {
                this["PATH_DATA_SAVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_CONVERT {
            get {
                return ((string)(this["PATH_CONVERT"]));
            }
            set {
                this["PATH_CONVERT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("depth")]
        public string CONV_PRESSURE_RANGE {
            get {
                return ((string)(this["CONV_PRESSURE_RANGE"]));
            }
            set {
                this["CONV_PRESSURE_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool INI_KEEP_MDP {
            get {
                return ((bool)(this["INI_KEEP_MDP"]));
            }
            set {
                this["INI_KEEP_MDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string INI_DOWNLOAD_SPEED {
            get {
                return ((string)(this["INI_DOWNLOAD_SPEED"]));
            }
            set {
                this["INI_DOWNLOAD_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CONV_CSV_SEPARATOR {
            get {
                return ((string)(this["CONV_CSV_SEPARATOR"]));
            }
            set {
                this["CONV_CSV_SEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string INI_DOWNLOAD_MODE {
            get {
                return ((string)(this["INI_DOWNLOAD_MODE"]));
            }
            set {
                this["INI_DOWNLOAD_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_GIPSY6_CONFIGURATION_EXPERT_MODE {
            get {
                return ((bool)(this["UI_GIPSY6_CONFIGURATION_EXPERT_MODE"]));
            }
            set {
                this["UI_GIPSY6_CONFIGURATION_EXPERT_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_GIPSY6_FIRMWARE_FILE {
            get {
                return ((string)(this["PATH_GIPSY6_FIRMWARE_FILE"]));
            }
            set {
                this["PATH_GIPSY6_FIRMWARE_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool INI_GIPSY6_BOOTLOADER_WIPE_DATA {
            get {
                return ((bool)(this["INI_GIPSY6_BOOTLOADER_WIPE_DATA"]));
            }
            set {
                this["INI_GIPSY6_BOOTLOADER_WIPE_DATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool INI_GIPSY6_BOOTLOADER_WIPE_SETTINGS {
            get {
                return ((bool)(this["INI_GIPSY6_BOOTLOADER_WIPE_SETTINGS"]));
            }
            set {
                this["INI_GIPSY6_BOOTLOADER_WIPE_SETTINGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONV_SPLIT_KML {
            get {
                return ((bool)(this["CONV_SPLIT_KML"]));
            }
            set {
                this["CONV_SPLIT_KML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CONV_SPLIT_KML_EVERY {
            get {
                return ((int)(this["CONV_SPLIT_KML_EVERY"]));
            }
            set {
                this["CONV_SPLIT_KML_EVERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("percentage")]
        public string UI_DEFAULT_BATTERY_UNIT {
            get {
                return ((string)(this["UI_DEFAULT_BATTERY_UNIT"]));
            }
            set {
                this["UI_DEFAULT_BATTERY_UNIT"] = value;
            }
        }
    }
}
